name: Bump Version Action
on:
  push:
    branches:
    - release/*
  workflow_dispatch:
jobs:
  bump_release_and_tox_build:
    env:
      OWNER: "bp4151"
      REPO: "cvss-rescore"
      CVSS_RESCORE_GH_TOKEN: ${{ secrets.CVSS_RESCORE_GH_TOKEN }}
    name: Bump release version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: run pip install and bump script
      run: |
        pip install -r .github/workflows/bump_version_requirements.txt
        python .github/workflows/bump_version.py
    - name: run tox build
      run: | 
        pip install tox setuptools
        tox -e build
        ls -lart dist
        echo "$RELEASE_TAG"
        
        FILES="dist/*"

        for FILE in $FILES
        do
          echo "${FILE}"
          if [[ ${FILE} == *.tar.gz ]]
          then
            mv ${FILE} dist/cvss_rescore_$RELEASE_TAG.tar.gz
          else
            mv ${FILE} dist/cvss_rescore_$RELEASE_TAG-py3-none-any.whl
          fi
        done

        
        gh release upload $RELEASE_TAG dist
