name: Bump Version Action
on:
  push:
    branches:
    - release/*
  workflow_dispatch:
jobs:
  bump_release:
    name: Bump release version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - name: run pip install and bump script
      run: |
        pip install -r .github/workflows/bump_version_requirements.txt
#  tox_build:
#    name: Build project using Tox
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: run tox build
#      run: | 
#        pip install tox setuptools
#        tox -e build
  
