name: TestPypi Package Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    env:
      TWINE_USERNAME: ${{ secrets.TEST_TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TEST_TWINE_PASSWORD }}
      TWINE_REPOSITORY: ${{ secrets.TEST_TWINE_REPOSITORY }}
      TWINE_REPOSITORY_URL: ${{ secrets.TEST_TWINE_REPOSITORY_URL }}
      GH_TOKEN: ${{ secrets.CVSS_RESCORE_GH_TOKEN }}
    name: TestPypi Package Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: run tox publish
      run: | 
        pip install tox setuptools twine
        mkdir dist
        cd dist
        gh release download v0.0.1
        cd ..
        ls -lart dist
        tox -e publish
