name: Label Release
on:
  push:
    branches:
    - release/*
  workflow_dispatch:
jobs:
  tox_build:
    name: Build project using Tox
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: run tox build
      run: | 
        pip install tox
        tox -e build
  
